services:
  postgres:
    image: postgres:alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ticketing
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # - ./init-scripts:/docker-entrypoint-initdb.d
    restart: always

  nestjs-ticketing-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-ticketing
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: test
      DATABASE_PASSWORD: password
      DATABASE_NAME: ticketing
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres-data: