export enum PROVIDER_NAMES {
    DATA_SOURCE = 'DATA_SOURCE',
    ENTITY_MANAGER = 'ENTITY_MANAGER',
    EVENTS_REPOSITORY = 'EVENTS_REPOSITORY',
    VENUE_REPOSITORY = 'VENUE_REPOSITORY',
    TICKET_REPOSITORY = 'TICKET_REPOSITORY',
    BOOKING_REPOSITORY = 'BOOKING_REPOSITORY',
    USER_REPOSITORY = 'USER_REPOSITORY'
}